// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../functions/_generated/api.js";

import type { InferInsertModel, InferSelectModel } from "better-convex/orm";
import type { tables } from "../functions/schema";

export const api = {
  database: {
    getMany: createApiLeaf<"query", typeof import("../functions/database").getMany>(convexApi["database"]["getMany"], { auth: "required", type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/database").getOne>(convexApi["database"]["getOne"], { auth: "required", type: "query" }),
    initial: createApiLeaf<"mutation", typeof import("../functions/database").initial>(convexApi["database"]["initial"], { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/database").update>(convexApi["database"]["update"], { auth: "required", type: "mutation" }),
  },
  organization: {
    accept: createApiLeaf<"mutation", typeof import("../functions/organization").accept>(convexApi["organization"]["accept"], { auth: "required", type: "mutation" }),
    addCustomIcon: createApiLeaf<"mutation", typeof import("../functions/organization").addCustomIcon>(convexApi["organization"]["addCustomIcon"], { auth: "required", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/organization").create>(convexApi["organization"]["create"], { auth: "required", ratelimit: "organization/create", type: "mutation" }),
    generateLink: createApiLeaf<"mutation", typeof import("../functions/organization").generateLink>(convexApi["organization"]["generateLink"], { auth: "required", type: "mutation" }),
    getActiveOrganization: createApiLeaf<"query", typeof import("../functions/organization").getActiveOrganization>(convexApi["organization"]["getActiveOrganization"], { auth: "required", type: "query" }),
    getInitialSession: createApiLeaf<"query", typeof import("../functions/organization").getInitialSession>(convexApi["organization"]["getInitialSession"], { type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/organization").getOne>(convexApi["organization"]["getOne"], { auth: "required", type: "query" }),
    invite: createApiLeaf<"mutation", typeof import("../functions/organization").invite>(convexApi["organization"]["invite"], { auth: "required", type: "mutation" }),
    join: createApiLeaf<"mutation", typeof import("../functions/organization").join>(convexApi["organization"]["join"], { auth: "required", type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/organization").list>(convexApi["organization"]["list"], { auth: "required", type: "query" }),
    reject: createApiLeaf<"mutation", typeof import("../functions/organization").reject>(convexApi["organization"]["reject"], { auth: "required", type: "mutation" }),
  },
  upload: {
    generateUploadUrl: createApiLeaf<"mutation", typeof import("../functions/upload").generateUploadUrl>(convexApi["upload"]["generateUploadUrl"], { auth: "required", type: "mutation" }),
  },
  user: {
    getCurrentUser: createApiLeaf<"query", typeof import("../functions/user").getCurrentUser>(convexApi["user"]["getCurrentUser"], { auth: "required", type: "query" }),
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
